[2023-03-30T17:43:59.560+0000] {processor.py:153} INFO - Started process (PID=3078) to work on /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
[2023-03-30T17:43:59.562+0000] {processor.py:743} INFO - Processing file /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py for tasks to queue
[2023-03-30T17:43:59.564+0000] {logging_mixin.py:137} INFO - [2023-03-30T17:43:59.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
[2023-03-30T17:44:29.576+0000] {logging_mixin.py:137} INFO - [2023-03-30T17:44:29.575+0000] {timeout.py:68} ERROR - Process timed out, PID: 3078
[2023-03-30T17:44:29.582+0000] {logging_mixin.py:137} INFO - [2023-03-30T17:44:29.577+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py", line 199, in <module>
    python_callable=extract_pokemon(),
  File "/workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py", line 40, in extract_pokemon
    response = requests.get(pokemon_url, timeout=1000)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 3078
[2023-03-30T17:44:29.584+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
[2023-03-30T17:44:29.606+0000] {processor.py:175} INFO - Processing /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py took 30.053 seconds
[2023-03-30T17:44:30.776+0000] {processor.py:153} INFO - Started process (PID=5164) to work on /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
[2023-03-30T17:44:30.777+0000] {processor.py:743} INFO - Processing file /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py for tasks to queue
[2023-03-30T17:44:30.778+0000] {logging_mixin.py:137} INFO - [2023-03-30T17:44:30.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
[2023-03-30T17:45:00.786+0000] {logging_mixin.py:137} INFO - [2023-03-30T17:45:00.786+0000] {timeout.py:68} ERROR - Process timed out, PID: 5164
[2023-03-30T17:45:00.791+0000] {logging_mixin.py:137} INFO - [2023-03-30T17:45:00.787+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py", line 199, in <module>
    python_callable=extract_pokemon(),
  File "/workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py", line 40, in extract_pokemon
    response = requests.get(pokemon_url, timeout=1000)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 5164
[2023-03-30T17:45:00.793+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
[2023-03-30T17:45:00.812+0000] {processor.py:175} INFO - Processing /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py took 30.038 seconds
[2023-03-30T17:45:01.915+0000] {processor.py:153} INFO - Started process (PID=6058) to work on /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
[2023-03-30T17:45:01.916+0000] {processor.py:743} INFO - Processing file /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py for tasks to queue
[2023-03-30T17:45:01.916+0000] {logging_mixin.py:137} INFO - [2023-03-30T17:45:01.916+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
[2023-03-30T17:45:31.926+0000] {logging_mixin.py:137} INFO - [2023-03-30T17:45:31.925+0000] {timeout.py:68} ERROR - Process timed out, PID: 6058
[2023-03-30T17:45:31.929+0000] {logging_mixin.py:137} INFO - [2023-03-30T17:45:31.926+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py", line 199, in <module>
    python_callable=extract_pokemon(),
  File "/workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py", line 40, in extract_pokemon
    response = requests.get(pokemon_url, timeout=1000)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 6058
[2023-03-30T17:45:31.931+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py
[2023-03-30T17:45:31.952+0000] {processor.py:175} INFO - Processing /workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py took 30.039 seconds
