[2023-04-03T10:22:37.069+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: pokeapi_dag.extract_moves manual__2023-04-03T10:20:17.209835+00:00 [queued]>
[2023-04-03T10:22:37.073+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: pokeapi_dag.extract_moves manual__2023-04-03T10:20:17.209835+00:00 [queued]>
[2023-04-03T10:22:37.074+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T10:22:37.074+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-04-03T10:22:37.074+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T10:22:37.156+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_moves> on 2023-04-03 10:20:17.209835+00:00
[2023-04-03T10:22:37.159+0000] {standard_task_runner.py:55} INFO - Started process 8429 to run task
[2023-04-03T10:22:37.161+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'pokeapi_dag', 'extract_moves', 'manual__2023-04-03T10:20:17.209835+00:00', '--job-id', '501', '--raw', '--subdir', 'DAGS_FOLDER/pokebase_to_s3.py', '--cfg-path', '/tmp/tmpq4yw7690']
[2023-04-03T10:22:37.162+0000] {standard_task_runner.py:83} INFO - Job 501: Subtask extract_moves
[2023-04-03T10:22:37.196+0000] {task_command.py:388} INFO - Running <TaskInstance: pokeapi_dag.extract_moves manual__2023-04-03T10:20:17.209835+00:00 [running]> on host 59f4bcb29cab
[2023-04-03T10:22:37.253+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pokeapi_dag
AIRFLOW_CTX_TASK_ID=extract_moves
AIRFLOW_CTX_EXECUTION_DATE=2023-04-03T10:20:17.209835+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-03T10:20:17.209835+00:00
[2023-04-03T10:25:59.520+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/workspaces/data-engineer-zoomcamp-project/airflow/dags/pokebase_to_s3.py", line 155, in extract_moves
    df = pd.DataFrame(moves_dict)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 663, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 493, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 118, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 666, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
[2023-04-03T10:25:59.529+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=pokeapi_dag, task_id=extract_moves, execution_date=20230403T102017, start_date=20230403T102237, end_date=20230403T102559
[2023-04-03T10:25:59.548+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 501 for task extract_moves (All arrays must be of the same length; 8429)
[2023-04-03T10:25:59.573+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-03T10:25:59.582+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
